version: '3.8'

services:
  website:
    build:
      context: ./docker_image
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/mydatabase
    networks:
      - app-network
    depends_on:
      - db
      
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "3000:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
